name: example-environment
channels:
  - conda-forge
  - tallic
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - seaborn
  - pandas-profiling
  - dfply